AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  S3bucketName:
    Type: String
    Default: "eeny5-b8266bd713"
  DeployName:
    Type: String
    Default: "Eeny2025"

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${DeployName}-lambda"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub "${DeployName}lambda"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action: dynamodb:*
                Resource: "*"

  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${DeployName}"
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: Name
          AttributeType: S
      KeySchema:
        - AttributeName: Name
          KeyType: HASH

  FetchFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${DeployName}-fetch2025"
      Runtime: python3.13
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Code:
        S3Bucket: !Sub "${S3bucketName}"
        S3Key: "fetch2025.zip"
      MemorySize: 256
